//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lollipop_Bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class useraccount
    {
        public int account_id { get; set; }
        public string name { get; set; }
        public string DOB { get; set; }
        public string phonenumber { get; set; }
        public string address { get; set; }
        public string state { get; set; }
        public string gender { get; set; }
        public string maritial_status { get; set; }
        public Nullable<decimal> balance { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    }
}
